"""init_multitenant_schema

Revision ID: 8b32aa108f5c
Revises: 
Create Date: 2026-05-01 22:10:09.153981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b32aa108f5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('code', sa.String(length=50), nullable=False, comment='machine code'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='human-readable name'),
    sa.Column('parent', sa.String(length=50), nullable=True, comment='parent category code; NULL for top-level'),
    sa.ForeignKeyConstraint(['parent'], ['categories.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code'),
    comment='Spending categories. Shared reference data.'
    )
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='legal name'),
    sa.Column('inn', sa.String(length=12), nullable=False, comment='Russian taxpayer identification number (10 or 12 digits)'),
    sa.Column('tier', sa.String(length=20), nullable=False, comment='commercial tier: standard | premium'),
    sa.CheckConstraint("tier in ('standard','premium')", name='ck_companies_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn'),
    comment='Client-companies (tenants) onboarded by the BaaS operator.'
    )
    op.create_table('currency_rates',
    sa.Column('base', sa.String(length=3), nullable=False, comment='base currency ISO 4217 code'),
    sa.Column('quote', sa.String(length=3), nullable=False, comment='quote currency ISO 4217 code'),
    sa.Column('date', sa.Date(), nullable=False, comment='rate snapshot date'),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False, comment='1 unit of base = rate units of quote'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='upstream provider id'),
    sa.PrimaryKeyConstraint('base', 'quote', 'date'),
    sa.UniqueConstraint('base', 'quote', 'date', name='uq_currency_rates_triple'),
    comment='Daily FX rates. Shared reference data.'
    )
    op.create_table('ingestion_state',
    sa.Column('doc_id', sa.String(length=200), nullable=False, comment='stable document identifier (path or slug)'),
    sa.Column('hash', sa.String(length=128), nullable=False, comment='content hash for change detection'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('doc_id'),
    comment='RAG ingestion bookkeeping. Shared (operator-wide).'
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='tenant identifier; SQL guard injects from authenticated user, never from LLM input'),
    sa.Column('user_role', sa.String(length=50), nullable=False, comment='role of the authenticated user that issued the action'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='event kind: sql_executed | sql_rejected | tenancy_rewrite | tenancy_violation'),
    sa.Column('sql_text', sa.Text(), nullable=True, comment='SQL statement after guard rewrites (if any)'),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False, comment='info | warning | high (cross-tenant incidents = high)'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='structured payload: violations, original SQL, errors'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity in ('info','warning','high')", name='ck_audit_severity'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Audit trail for SQL requests + tenancy isolation incidents. Tenancy-aware.'
    )
    op.create_index('ix_audit_log_company_id', 'audit_log', ['company_id'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='tenant identifier; SQL guard injects from authenticated user, never from LLM input'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Employees of a client-company. Tenancy-aware.'
    )
    op.create_index('ix_employees_company_id', 'employees', ['company_id'], unique=False)
    op.create_table('limits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='tenant identifier; SQL guard injects from authenticated user, never from LLM input'),
    sa.Column('subject_type', sa.String(length=20), nullable=False, comment='company | employee | card | category'),
    sa.Column('subject_id', sa.String(length=50), nullable=True, comment="reference id matching subject_type (NULL when subject_type='company')"),
    sa.Column('period', sa.String(length=20), nullable=False, comment='day | week | month | quarter | year'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.CheckConstraint("period in ('day','week','month','quarter','year')", name='ck_limits_period'),
    sa.CheckConstraint("subject_type in ('company','employee','card','category')", name='ck_limits_subject_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Spending limits — per company / employee / card / category. Tenancy-aware.'
    )
    op.create_index('ix_limits_company_id', 'limits', ['company_id'], unique=False)
    op.create_table('payout_recipients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='tenant identifier; SQL guard injects from authenticated user, never from LLM input'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='individual | company'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True, comment='Russian taxpayer id; sensitive — restricted columns'),
    sa.Column('account', sa.String(length=34), nullable=True, comment='bank account; sensitive — restricted columns'),
    sa.CheckConstraint("type in ('individual','company')", name='ck_recipients_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Counterparties that receive payouts from a tenant. Tenancy-aware.'
    )
    op.create_index('ix_payout_recipients_company_id', 'payout_recipients', ['company_id'], unique=False)
    op.create_table('reason_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True, comment='default category this reason code maps to'),
    sa.ForeignKeyConstraint(['category'], ['categories.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code'),
    comment='Reason codes (operational classifiers). Shared reference data.'
    )
    op.create_table('report_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='tenant identifier; SQL guard injects from authenticated user, never from LLM input'),
    sa.Column('report_type', sa.String(length=30), nullable=False, comment='monthly | quarterly | annual | reconciliation'),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='structured snapshot: totals by category, fees, anomalies, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("report_type in ('monthly','quarterly','annual','reconciliation')", name='ck_report_snapshots_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Periodic report snapshots (closed periods). Tenancy-aware.'
    )
    op.create_index('ix_report_snapshots_company_id', 'report_snapshots', ['company_id'], unique=False)
    op.create_index('ix_report_snapshots_company_period', 'report_snapshots', ['company_id', 'period_start', 'period_end'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='tenant identifier; SQL guard injects from authenticated user, never from LLM input'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='human-readable plan name'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active | inactive | draft'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='first day the tariff applies (inclusive)'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='last day the tariff applies (inclusive); NULL = open-ended'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='default currency for fees in this tariff'),
    sa.CheckConstraint("status in ('active','inactive','draft')", name='ck_tariffs_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Operator tariff plans assigned to partner companies. Tenancy-aware.'
    )
    op.create_index('ix_tariffs_company_id', 'tariffs', ['company_id'], unique=False)
    op.create_index('ix_tariffs_company_status', 'tariffs', ['company_id', 'status'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='tenant identifier; SQL guard injects from authenticated user, never from LLM input'),
    sa.Column('employee_id', sa.BigInteger(), nullable=False, comment='cardholder'),
    sa.Column('last4', sa.String(length=4), nullable=False, comment='last 4 digits of PAN'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active | blocked | expired'),
    sa.Column('limit_monthly', sa.Numeric(precision=15, scale=2), nullable=False, comment='monthly spending limit in card currency'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='ISO 4217 code'),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','blocked','expired')", name='ck_cards_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Corporate cards issued to employees. Tenancy-aware.'
    )
    op.create_index('ix_cards_company_id', 'cards', ['company_id'], unique=False)
    op.create_index('ix_cards_employee_id', 'cards', ['employee_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='tenant identifier; SQL guard injects from authenticated user, never from LLM input'),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='operator fee charged for this payout in the same currency'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | approved | rejected | executed'),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('pending','approved','rejected','executed')", name='ck_payouts_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reason_code'], ['reason_codes.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['payout_recipients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Outgoing payouts (vendor / contractor / employee reimbursements). Tenancy-aware.'
    )
    op.create_index('ix_payouts_company_created_at', 'payouts', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_payouts_company_id', 'payouts', ['company_id'], unique=False)
    op.create_index('ix_payouts_recipient_id', 'payouts', ['recipient_id'], unique=False)
    op.create_table('tariff_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tariff_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='tenant identifier; SQL guard injects from authenticated user, never from LLM input'),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='card_payment | payout_individual | payout_company | currency_conversion'),
    sa.Column('fee_type', sa.String(length=20), nullable=False, comment='fixed | percent | combined (fixed + percent)'),
    sa.Column('amount_fixed', sa.Numeric(precision=15, scale=2), nullable=True, comment='fixed fee component (NULL for pure percent)'),
    sa.Column('amount_percent', sa.Numeric(precision=7, scale=4), nullable=True, comment='percent fee component, e.g. 1.5000 = 1.5%'),
    sa.Column('min_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('max_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('conditions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='optional structured conditions (mcc whitelist, amount thresholds, etc.)'),
    sa.CheckConstraint("fee_type in ('fixed','percent','combined')", name='ck_tariff_rules_fee_type'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Fee rules attached to a tariff (1 rule per operation_type). Tenancy-aware.'
    )
    op.create_index('ix_tariff_rules_company_id', 'tariff_rules', ['company_id'], unique=False)
    op.create_index('ix_tariff_rules_tariff_id', 'tariff_rules', ['tariff_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False, comment='tenant identifier; SQL guard injects from authenticated user, never from LLM input'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='positive value in transaction currency'),
    sa.Column('fee_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='operator fee charged for this transaction in the same currency'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('mcc', sa.String(length=4), nullable=True, comment='merchant category code (4 digits)'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='resolved category code'),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='approved | declined | reversed'),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('approved','declined','reversed')", name='ck_transactions_status'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category'], ['categories.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reason_code'], ['reason_codes.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Card transactions. Tenancy-aware.'
    )
    op.create_index('ix_transactions_card_id', 'transactions', ['card_id'], unique=False)
    op.create_index('ix_transactions_company_created_at', 'transactions', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_transactions_company_id', 'transactions', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_company_id', table_name='transactions')
    op.drop_index('ix_transactions_company_created_at', table_name='transactions')
    op.drop_index('ix_transactions_card_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_tariff_rules_tariff_id', table_name='tariff_rules')
    op.drop_index('ix_tariff_rules_company_id', table_name='tariff_rules')
    op.drop_table('tariff_rules')
    op.drop_index('ix_payouts_recipient_id', table_name='payouts')
    op.drop_index('ix_payouts_company_id', table_name='payouts')
    op.drop_index('ix_payouts_company_created_at', table_name='payouts')
    op.drop_table('payouts')
    op.drop_index('ix_cards_employee_id', table_name='cards')
    op.drop_index('ix_cards_company_id', table_name='cards')
    op.drop_table('cards')
    op.drop_index('ix_tariffs_company_status', table_name='tariffs')
    op.drop_index('ix_tariffs_company_id', table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index('ix_report_snapshots_company_period', table_name='report_snapshots')
    op.drop_index('ix_report_snapshots_company_id', table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_table('reason_codes')
    op.drop_index('ix_payout_recipients_company_id', table_name='payout_recipients')
    op.drop_table('payout_recipients')
    op.drop_index('ix_limits_company_id', table_name='limits')
    op.drop_table('limits')
    op.drop_index('ix_employees_company_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_company_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('ingestion_state')
    op.drop_table('currency_rates')
    op.drop_table('companies')
    op.drop_table('categories')
    # ### end Alembic commands ###
